### ISSUE TITLE
does not build for me...

### ISSUE THREAD

**Issue by df8oe** [bartoszek/AUR-scilab-git#2]
Arch amd64. I have installed scilab 6.1.0-5 that builds and works without problems. Scilab 6.1.1-1 does not build anymore and causes same warnings and error messages as scilab-git 6.2.0.r216.g81a9cc04933-1:
1)`The library attempted to open the following supporting CUDA libraries,
but each of them failed.  CUDA-aware support is disabled.
libcuda.so.1: cannot open shared object file: No such file or directory
libcuda.dylib: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.so.1: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.dylib: cannot open shared object file: No such file or directory
If you are not interested in CUDA-aware support, then run with
--mca opal_warn_on_missing_libcuda 0 to suppress this message.  If you are interested
in CUDA-aware support, then try setting LD_LIBRARY_PATH to the location
of libcuda.so.1 to get passed this issue.
`
2)`Warning: Could not find Java package '/home/andreas/.cache/yay/scilab-git/src/scilab/scilab/thirdparty/ecj.jar'.
`
3)`The native library scicommons does not exist or cannot be found.
/home/user/.cache/yay/scilab-git/src/scilab/scilab/modules/xcos/.libs/libscixcos.so.6.1.1: /home/user/.cache/yay/scilab-git/src/scilab/scilab/modules/scicos/.libs/libsciscicos.so.6: undefined symbol: _ZN8Overload4callERKNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEERSt6vectorIPN5types12InternalTypeESaISB_EEiSE_bbRK8Location`

**Comment by bartoszek** [comment]
Sorry, can't reproduce the issue, builds and works fine here both scilab & scilab-git ( only issue I've encounter was outdated source link in` the `apache-lucent` package ) 

Could you perhaps provide verbose build log, preferably in clean container...

**Comment by df8oe** [comment]
Absolutely strange. I have treid it 3...4 times with scilab and scilab-git yesterday and this morning - always no succes.. Also I tried a "clean build option" at yay - no success. So I deleted complete folders ~/.cache/yay/scilab and scilab git and gave it a new try. The warnings still remain - but the build completes. Seems to be garbage in the  working folder here. Thanks for your fast statement and for your work to provide this nice piece of software! I am using is for softare defined radio development purposes and it helps much.

**Comment by bartoszek** [comment]
There could be some automatical dependencies that reside on your system and are missing from depends, makedenends. Could you help me up and post your system stat `pacman -Q` so I can test it further? And maybe if their're any list of software installed directly to `/usr/local` thanks.

**Comment by df8oe** [comment]
I do not think that would help much. But I have another machine (my notebook) where a nearly identical software configuration is present. Only packages from Arch repositories and AURs. It seems that I am running there in identical trouble. first is that some libraries of libicu cannot found because they are searched for "68" version - but on the system "69" is present. I have solved that at my main working machine by symlinking. At the notebook I have stopped now after scilab cannot be build because of "68" is searched but "69" is present. Now I try to build scilab-git (it lasts hours there) for it is a virgin build. I will report and do nothing without introducing you / answering to possible questions. Sorry for this kind of complicated going on but possibly the reason(s) can be found.

**Comment by df8oe** [comment]
OK - lets begin. Everything I mention here is also present at AUR-scilab.
First issue:
`LANG=en_US.UTF-8 LC_ALL=C SCI_DISABLE_TK=1 SCI_JAVA_ENABLE_HEADLESS=1 _JAVA_OPTIONS='-Djava.awt.headless=true' HOME=/tmp ./bin/scilab-adv-cli -noatomsautoload -nb -l en_US -nouserstartup -e "try xmltojar([],[],'en_US');catch disp(lasterror()); exit(-1);end;exit(0);"
/home/user/.cache/yay/scilab-git/src/scilab/scilab/.libs/lt-scilab-bin: error while loading shared libraries: libicui18n.so.68: cannot open shared object file: No such file or directory
make: *** [Makefile:2250: doc] Fehler 1
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...`

This is because at my systems icu has the version 69.1-1. Something is looking for version 68 instead. Can be solved by looking for library without version string, or (how I solved this - but not elegant, because it is a manual intervention) by creating symlinks which are named as 68 version.

**Comment by bartoszek** [comment]
This is merely an issue that arises when packages got outdated when it's dependencies receive an update. Most of the time `rebuild-detector` can pick up witch packages own a file that has "dangling" library reference and report this during the system upgrade https://archlinux.org/packages/community/any/rebuild-detector/

You can call `checkrebuild` to print the list of outdated packages or examine last `rebuild-detector` section in `/var/log/pacman.log` for the same list of outdated packages.

If I may suggest something for the future, instead of fighting against your system you could spare yourself lots of trouble by spinning up ephemeral container to build your packages in. The successor of `yay` -> `paru` has this function included with `-c/--chroot` option and it's interface is compatible with `yay` so switching shouldn't be a problem.

https://github.com/Morganamilo/paru/pull/118

If you would rather keep `yay` around, you can always spin up local container with `mkarchroot ${dst_dir} base-devel git vim` giving it the list of packages to pull from the Arch repos and chroot into it with `arch-nspawn ${dst_dir}` then add and switch to local user account `useradd ${user}; passwd ${user}; echo "${user} ALL=(ALL) ALL" >>/etc/sudoers"; mkdir /home/${user}; chown ${user} /home/${user}; su ${user}` then pull `yay` from AUR `git clone https://aur.archlinux.org/yay-bin.git` and build it with `make -si` and proceed from there with `yay -S scilab`. If the package builds fine you'll find the installation files *.pkg.tar.zst in `${dst_dir}/home/${user}/.cache/yay/${pkgname}`

**Comment by df8oe** [comment]
Many thanks for helping me so much. I didn't know rebuild-detector before (but I often have missed such a tool), and I tried first time paru with building in chroot directly. Both things are much important learnings for me - thank you again! But building in a chroot fails, too because of missing  'apache-lucene 8.8.2-1' which is no longer available. I dig into apache download sites and recognized that https://downloads.apache.org/lucene/java/8.9.0/lucene-8.9.0-src.tgz is be the correct address now - I fixed this in apache-lucene PKGBUILD and updated checksum. Now everything builds fine. Not an issue at your side at all.
